### ISSUE TITLE
Definir Keynotes

### ISSUE THREAD

**Issue by DennyPerez18** [githubpresente/octogatosconf22#1]
Postular personas que serían apropiadas para ser keynotes de la conferencia.

Lo importante es que sean personas reconocidas en alguna comunidad 
Que hablen español o portugués (en lo posible)
Que estén involucradas en algún proyecto o iniciativa conocida
Que su presencia signifique atraer a distintos grupos de personas de comunidades diversas

-----
La información necesaria para postular a personas es:
* **Nombre**
* **Web** (Red social, sitio personal, etc)
* **Justificación** (razón que crean que es importante para considerarla)

**Comment by AndreaGriffiths11** [comment]
Nina da Hora
Juan Pablo Buritica
Mario Rodriguez

**Comment by DennyPerez18** [comment]
Hey @AndreaGriffiths11 Can we ask the keynotes to send us a short bio?

**Comment by AndreaGriffiths11** [comment]
Best selections by the best! 🚢
