### ISSUE TITLE
Selection Comittee PORTUGUESE content

### ISSUE THREAD

**Issue by AndreaGriffiths11** [githubpresente/octogatosconf22#11]
## Members 

- @pachicodes
- Lara Marcos
- @pedrolacerda

## Sessions

TBD

**Comment by GiovanaNp1** [comment]
Olá, primeiramente obrigada a Github e octogatosConf22 pela oportunidade, sou Giovana do Nascimento, sou application Developer fullstack na IBM a quase 4 anos. Sou formada em análise e desenvolvimento de sistemas e nas horas vagas gosto de palestrar, participar de eventos, dar aulas e entre outros.

**Comment by AndreaGriffiths11** [comment]
Best selections by the best! 🚢
