### ISSUE TITLE
Spanish corrections

### ISSUE THREAD

**Issue by juanpflores** [githubpresente/octogatosconf22#9]
<img width="256" alt="image" src="https://user-images.githubusercontent.com/6200135/176486863-74729f58-8f84-4c64-82f0-d1334c397ca1.png">
This is a gendered call-out. Let's change this to "Proponer charla" or "Enviar propuesta de charla"

<img width="105" alt="image" src="https://user-images.githubusercontent.com/6200135/176487366-d39f8de3-a8a0-4430-ae68-f42e2dc910b5.png">
Cambiar oradores por "Agenda" o "Charlas" 

<img width="316" alt="image" src="https://user-images.githubusercontent.com/6200135/176487496-d07f383a-ca4b-4768-8aa2-c109f4f8e5f9.png">
Cambiar "Registro gratis" por "Registro Gratuito"

<img width="416" alt="image" src="https://user-images.githubusercontent.com/6200135/176487638-1e2aa52c-cc8d-4ab2-a195-7950d5e4f5eb.png">
Cambiar "Agregar sesion a google calendar" for "Agregar a google calendar"

<img width="847" alt="image" src="https://user-images.githubusercontent.com/6200135/176487872-66544d76-6737-4e01-bce0-b2a08cc377e6.png">

Change "Una conferencia en vivo gratuita el 15 de septiembre de 2022 en la celebración de nuestra cultura durante el mes del..." for "Una conferencia en vivo gratuita el 15 de septiembre de 2022 en la celebración de la cultura durante el mes del..."

<img width="872" alt="image" src="https://user-images.githubusercontent.com/6200135/176488136-2c65065f-8302-4e3c-bf08-d9a920e2e00c.png">

Change "Te unirás a una transmisión en vivo de charlas interactivas por parte de expertos de la industria en español, portugués e inglés, con traducción." for "Únete a una transmisión en vivo de charlas interactivas por parte de expertos de la industria en español, portugués e inglés, con traducción en multiple idiomas."

<img width="903" alt="image" src="https://user-images.githubusercontent.com/6200135/176488579-fa3fcc16-333b-41e0-8fbc-6bcbba4695f7.png">

Add "Diversidad e Inclusion"
Change "La seguridad" for "Seguridad"

**Comment by AndreaGriffiths11** [comment]
Done
